export const GET_USERS_SAGA = "GET_USERS_SAGA";
export const SAVE_USER_SAGA = "SAVE_USER_SAGA";
export const REMOVE_USER_SAGA = "REMOVE_USER_SAGA";
export const GET_USERS_BY_NAME_SAGA = "GET_USERS_BY_NAME_SAGA";