export const CHANGE_EMAIL_IN = "CHANGE_EMAIL_IN";
export const CHANGE_PASSWORD_IN = "CHANGE_PASSWORD_IN";
export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_LAST_NAME = "CHANGE_LAST_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_PHONE = "CHANGE_PHONE";
export const CHANGE_PHOTO = "CHANGE_PHOTO";
export const CHANGE_CHECKBOX = "CHANGE_CHECKBOX";

export const CLEAR_SIGN_IN = "CLEAR_SIGN_IN";
export const CLEAR_SIGN_UP = "CLEAR_SIGN_UP";