export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CHANGE_FILTERED_NAME = 'CHANGE_FILTERED_NAME';

export const UPDATE_ID = 'UPDATE_ID';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';

export const SWAP = 'SWAP';

export const PUT_PRODUCT_TO_FORM = 'PUT_PRODUCT_TO_FORM';
export const CLEAR_PRODUCT_FORM = 'CLEAR_PRODUCT_FORM';

export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
export const GET_PRODUCT_BY_ID_SAGA = 'GET_PRODUCT_BY_ID_SAGA';
export const SAVE_PRODUCT_SAGA = 'SAVE_PRODUCT_SAGA';
export const DELETE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA';