export const GET_PRODUCTS_SAGA = "GET_PRODUCTS_SAGA";
export const GET_PRODUCTS_BY_NAME_SAGA = "GET_PRODUCTS_BY_NAME_SAGA";
export const SAVE_PRODUCT_SAGA = "SAVE_PRODUCT_SAGA";
export const REMOVE_PRODUCT_SAGA = "REMOVE_PRODUCT_SAGA";