export const GET_PRODUCTS_SAGA = "GET_PRODUCTS_SAGA";
export const GET_PRODUCTS_BY_NAME_SAGA = "GET_PRODUCTS_BY_NAME_SAGA";
export const SAVE_PRODUCT_SAGA = "SAVE_PRODUCT_SAGA";
export const DELETE_PRODUCT_SAGA = "UPDATE_PRODUCT_SAGA";