export const CHANGE_USER_ID = 'CHANGE_USER_ID';
export const CHANGE_USER_FIRST_NAME = 'CHANGE_USER_FIRST_NAME';
export const CHANGE_USER_LAST_NAME = 'CHANGE_USER_LAST_NAME';
export const CHANGE_USER_PHONE_NUMBER = 'CHANGE_USER_PHONE_NUMBER';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_PHOTO = 'CHANGE_USER_PHOTO';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';

export const SET_USERS = 'SET_USERS';
export const SAVE_USER = 'SAVE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const CHANGE_FILTERED_USERNAME = 'CHANGE_FILTERED_USERNAME';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PUT_USER_TO_FORM = 'PUT_USER_TO_FORM';
export const CLEAR_USER_FORM = 'CLEAR_USER_FORM';

export const GET_USERS_SAGA = 'GET_USERS_SAGA';
export const SAVE_USER_SAGA = 'SAVE_USER_SAGA';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';
export const GET_USERS_BY_NAME_SAGA = 'GET_USERS_BY_NAME_SAGA';