export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

export const UPDATE_ID = 'UPDATE_ID';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';

export const PUT_PRODUCT_TO_FORM = 'PUT_PRODUCT_TO_FORM';

export const CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'CHANGE_LAST_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX';

export const SWAP = 'SWAP';
export const CREATE = 'CREATE';
export const LOG_IN = 'LOG_IN';
